### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by 0xWraith** [AVO-cado-team/ram-webgui#9]
1. ~~No loader~~
2. ~~No console~~
3. ~~Editor takes 50% of its space~~
4. ~~Register menu is different~~
5. ~~Fonts~~
6. Default code
7. ~~Input line is too big~~
8. ~~About us only closes when clicked button About us~~
9. About us pop-up window isn't adaptive

**Comment by Ddystopia** [comment]
Feel free to PR for 6 and 9

**Comment by Ddystopia** [comment]
About loader, it will be fixed later

**Comment by Ddystopia** [comment]
Closing, because loader would be obsolete with server-side rendering
